# Generated by Django 4.1.6 on 2023-02-06 12:11

import animals.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/')),
                ('species', models.CharField(choices=[('Cat', 'CAT'), ('Dog', 'DOG'), ('Hamster', 'HAMSTER')], default='cat', max_length=10)),
                ('age', models.PositiveSmallIntegerField(validators=[animals.models.birth_date_validation])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Animals',
            },
        ),
    ]
