# Generated by Django 4.1.6 on 2023-02-06 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='age',
            new_name='year_of_birth',
        ),
    ]
