# Generated by Django 4.1.6 on 2023-02-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_rename_animal_pet_alter_pet_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='image',
        ),
    ]
